//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace point_counter_for_uni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int Point_SK { get; set; }
        public double Point1 { get; set; }
        public int StudxSub_FK { get; set; }
        public int PT_FK { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual Max_type_points Max_type_points { get; set; }
        public virtual StudxSub StudxSub { get; set; }
    }
}
