//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace point_counter_for_uni
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentxUniversity
    {
        public int su_SK { get; set; }
        public string NEPTUN_FK { get; set; }
        public string Uni_FK { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
